name = "adao/vesting"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'adao/vesting'"

[repository]
user = "adao"
project = "vesting"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
